feature: build complete updater
elixir-cloud-aai/Pubgrade pull request #15
Opened 2022-04-09 09:38 UTC by akash2237778

Build complete updater: This container runs a script at specified intervals which removes the executed kaniko pods (in completed state).

2022-04-12 06:47 UTC, lvarin requested changes

2022-04-12 06:47 UTC, lvarin commented on build-complete-updater/updater.py
> +BUILD_ID_LENGTH = 6
Just to future proof this a bit, this parameter should be able to be configurable with environment variables.

2022-04-12 06:47 UTC, lvarin commented on build-complete-updater/updater.py
> +SLEEP_INTERVAL = 5
Just to future proof this a bit, this parameter should be able to be configurable with environment variables.

2022-04-12 06:47 UTC, lvarin commented on build-complete-updater/updater.py
> +                    and "ACCESSTOKEN" == pod.spec.containers[0].env[1].name
This assumes the order in which the environment variables will be in the Pod. There must be a better way to do this. Even this O(n) method is a better approach:

```
def getEnv(env, name):
    for var in env:
        if var.name == name:
            return var.value
```

2022-06-01 06:54 UTC, uniqueg approved these changes
If you address @lvarin's comments, it's fine with me.

2022-06-28 09:23 UTC, lvarin approved these changes
LGTM

2022-06-28 09:25 UTC, merged